config/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from auth_login.forms import LoginForm

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', auth_views.LoginView.as_view(
        template_name='auth_login/login.html',
        authentication_form=LoginForm), name='login'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(
        next_page='/'), name='logout'),
    path('u/', include('profiles.urls'), name='profiles')
]

profiles/urls.py
from django.urls import path

from .views import ProfileListView
from . import views

app_name = 'profiles'

urlpatterns = [
    path('', ProfileListView.as_view(), name='list'),
    path('create/', views.profile_create, name='create'),
    path('<int:pk>/edit/', views.profile_edit, name='update'),
    path('<int:pk>/edit/password/', views.admin_edit_password, name='admin_password_update'),
    path('create/group/', views.group_create, name='create_group'),
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group


# Create your models here.
class User(AbstractUser):
    group = models.ForeignKey(
        Group,
        related_name='profile_user_group',
        default=None,
        null=True,
        on_delete=models.CASCADE
    )
    user_id = models.CharField(max_length=50, null=True, blank=True)
    email = models.CharField(max_length=255, unique=True)
    designation = models.CharField(max_length=255, null=True, blank=True)
    mobile = models.CharField(max_length=100, null=True, blank=True)
    direct_line = models.CharField(max_length=100, null=True, blank=True)
    other_phone = models.CharField(max_length=100, null=True, blank=True)
    fax = models.CharField(max_length=255, null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    date_updated = models.DateTimeField(auto_now=True)

profiles/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group, Permission
from django.contrib.auth.forms import (
    UserCreationForm, UserChangeForm, AdminPasswordChangeForm
)


User = get_user_model()


class AdminGroupForm(ModelForm):
    name = forms.CharField(max_length=100,
                           widget=forms.TextInput(
                               attrs={
                                   'class': 'form-control'}))

    # permissions = forms.ModelMultipleChoiceField(
    #     Permission.objects.all(),
    #     widget=forms.CheckboxSelectMultiple())

    class Meta:
        model = Group
        fields = '__all__'


class ProfileCreationForm(UserCreationForm):
    group = forms.ModelChoiceField(queryset=Group.objects.all(),
                                   widget=forms.Select(
                                       attrs={
                                           'class': 'form-control'}))
    username = forms.CharField(max_length=100,
                               widget=forms.TextInput(
                                   attrs={
                                       'class': 'form-control'}))
    password1 = forms.CharField(max_length=100,
                                widget=forms.PasswordInput(
                                    attrs={
                                        'class': 'form-control'}))
    password2 = forms.CharField(max_length=100,
                                widget=forms.PasswordInput(
                                    attrs={
                                        'class': 'form-control'}))
    first_name = forms.CharField(max_length=100,
                                 widget=forms.TextInput(
                                     attrs={
                                         'class': 'form-control'}))
    last_name = forms.CharField(max_length=100,
                                widget=forms.TextInput(
                                    attrs={
                                        'class': 'form-control'}))
    email = forms.EmailField(max_length=200,
                             widget=forms.TextInput(
                                 attrs={
                                     'class': 'form-control'}))
    designation = forms.CharField(max_length=100,
                                  required=False,
                                  widget=forms.TextInput(
                                      attrs={
                                          'class': 'form-control',
                                          'name': 'designation'}))
    mobile = forms.CharField(max_length=100,
                             required=False,
                             widget=forms.TextInput(
                                 attrs={
                                     'class': 'form-control',
                                     'name': 'mobile'}))
    direct_line = forms.CharField(max_length=100,
                                  required=False,
                                  widget=forms.TextInput(
                                      attrs={
                                          'class': 'form-control',
                                          'name': 'direct_line'}))
    other_phone = forms.CharField(max_length=100,
                                  required=False,
                                  widget=forms.TextInput(
                                      attrs={
                                          'class': 'form-control',
                                          'name': 'other_phone'}))
    fax = forms.CharField(max_length=100,
                          required=False,
                          widget=forms.TextInput(
                              attrs={
                                  'class': 'form-control',
                                  'name': 'fax'}))
    notes = forms.CharField(max_length=100,
                            required=False,
                            widget=forms.Textarea(
                                attrs={
                                    'class': 'form-control',
                                    'name': 'notes',
                                    'rows': '5'}))

    class Meta:
        model = User
        fields = (
            'group',
            'username',
            'password1',
            'password2',
            'first_name',
            'last_name',
            'email',
            'designation',
            'mobile',
            'direct_line',
            'other_phone',
            'fax',
            'notes'
        )

    def save(self, commit=True):
        user = super(ProfileCreationForm, self).save(commit=False)
        user.group = self.cleaned_data['group']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.designation = self.cleaned_data['designation']
        user.mobile = self.cleaned_data['mobile']
        user.direct_line = self.cleaned_data['direct_line']
        user.other_phone = self.cleaned_data['other_phone']
        user.fax = self.cleaned_data['fax']
        user.notes = self.cleaned_data['notes']

        if commit:
            user.save()
        return user


class EditProfileForm(UserChangeForm):
    group = forms.ModelChoiceField(queryset=Group.objects.all(),
                                   widget=forms.Select(
                                       attrs={
                                           'class': 'form-control'}))
    username = forms.CharField(max_length=100,
                               widget=forms.TextInput(
                                   attrs={
                                       'class': 'form-control'}))
    first_name = forms.CharField(max_length=100,
                                 widget=forms.TextInput(
                                     attrs={
                                         'class': 'form-control'}))
    last_name = forms.CharField(max_length=100,
                                widget=forms.TextInput(
                                    attrs={
                                        'class': 'form-control'}))
    email = forms.EmailField(max_length=200,
                             widget=forms.TextInput(
                                 attrs={
                                     'class': 'form-control'}))
    designation = forms.CharField(max_length=100,
                                  required=False,
                                  widget=forms.TextInput(
                                      attrs={
                                          'class': 'form-control',
                                          'name': 'designation'}))
    mobile = forms.CharField(max_length=100,
                             required=False,
                             widget=forms.TextInput(
                                 attrs={
                                     'class': 'form-control',
                                     'name': 'mobile'}))
    direct_line = forms.CharField(max_length=100,
                                  required=False,
                                  widget=forms.TextInput(
                                      attrs={
                                          'class': 'form-control',
                                          'name': 'direct_line'}))
    other_phone = forms.CharField(max_length=100,
                                  required=False,
                                  widget=forms.TextInput(
                                      attrs={
                                          'class': 'form-control',
                                          'name': 'other_phone'}))
    fax = forms.CharField(max_length=100,
                          required=False,
                          widget=forms.TextInput(
                              attrs={
                                  'class': 'form-control',
                                  'name': 'fax'}))
    notes = forms.CharField(max_length=100,
                            required=False,
                            widget=forms.Textarea(
                                attrs={
                                    'class': 'form-control',
                                    'name': 'notes',
                                    'rows': '5'}))

    class Meta:
        model = User
        fields = (
            'group',
            'username',
            'password',
            'first_name',
            'last_name',
            'email',
            'designation',
            'mobile',
            'direct_line',
            'other_phone',
            'fax',
            'notes'
        )


class AdminEditPasswordForm(AdminPasswordChangeForm):
    password1 = forms.CharField(max_length=100,
                                widget=forms.PasswordInput(
                                    attrs={
                                        'class': 'form-control'}))
    password2 = forms.CharField(max_length=100,
                                widget=forms.PasswordInput(
                                    attrs={
                                        'class': 'form-control'}))

profiles/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.contrib.auth.models import ContentType, Permission
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView
from profiles.forms import (
    ProfileCreationForm, EditProfileForm, AdminEditPasswordForm,
    AdminGroupForm,
)
from .utils import unique_id_generator

# Create your views here.
User = get_user_model()


class ProfileListView(LoginRequiredMixin, ListView):
    model = User

    def get_context_data(self, **kwargs):
        context = super(ProfileListView, self).get_context_data(**kwargs)
        return context


@login_required
def profile_create(request):
    form = ProfileCreationForm(request.POST or None)
    if form.is_valid():
        user = form.save()
        uid = User.objects.get(id=user.id)
        uid.user_id = unique_id_generator(user.id)
        uid.save()
        return redirect('/u')

    template_name = 'profiles/user_create.html'
    context = {'form': form}
    return render(request, template_name, context)


@login_required
def profile_edit(request, pk):
    user = get_object_or_404(User, id=pk)
    form = EditProfileForm(request.POST or None, instance=user)
    if form.is_valid():
        form.save()
        return redirect('/u')

    template_name = 'profiles/user_edit.html'
    context = {'form': form, 'id': pk}
    return render(request, template_name, context)


@login_required
def admin_edit_password(request, pk):
    user = get_object_or_404(User, id=pk)
    form = AdminEditPasswordForm(data=request.POST or None, user=user)
    if form.is_valid():
        form.save()
        return redirect('/u')

    template_name = 'profiles/user_admin_edit_password.html'
    context = {'form': form}
    return render(request, template_name, context)


@login_required
def group_create(request):
    form = AdminGroupForm(request.POST or None)
    content_types = ContentType.objects.all()
    permissions = Permission.objects.all()
    if form.is_valid():
        form.save()
        return redirect('/u')

    template_name = 'profiles/group_create.html'
    context = {
        'form': form,
        'content_types': content_types,
        'permissions': permissions
    }
    return render(request, template_name, context)

profiles/templates/profiles/group_create.html
{% extends "base.html" %}

{% block page_title %} Group {% endblock page_title %}


{% block content %}

<section class="content">

  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Add User Group</h3>
    </div>

    <form class="form-horizontal" method="POST" novalidate>
      {% csrf_token %}
      <div class="box-body">
        <div class="form-group {% if form.name.errors %} has-error {% endif %}">
          <label for="" class="col-md-2 control-label">Name:</label>
          <div class="col-md-4">
            {{ form.name }}
            <span class="help-block">{{ form.name.errors }}</span>
          </div>
        </div>

        <div class="form-group {% if form.permissions.errors %} has-error {% endif %}">
          <label for="" class="col-md-2 control-label">Permissions:</label>
          <div class="col-md-10">
            {% for content_type in content_types  %}
              <h5><label>{{ content_type.app_label|title }} | {{ content_type.model|title }}</label></h5>

                {% for permission in permissions  %}
                    {% if content_type.id == permission.content_type_id %}
                        <div class="checkbox-inline">
                          <input type="checkbox" name="permissions" id="id_permissions" value="{{permission.id}}"> {{ permission.name }}
                        </div>
                    {% endif %}
                {% endfor %}
                <br><br>
            {% endfor %}
            <span class="help-block">{{ form.permissions.errors }}</span>
          </div>
        </div>


      </div>

      <div class="box-footer">
        <button type="submit" class="btn btn-primary">Save</button>
      </div>

    </form>

  </div>


</section>

{% endblock content %}

{% block script %}

{% endblock script %}

profiles/templates/profiles/index.html
{% extends "base.html" %}

{% block page_title %} Users {% endblock page_title %}


{% block content %}

<section class="content">

  <div class="box">
    <div class="box-header with-border">
      <h3 class="box-title">Title</h3>

      <div class="box-tools pull-right">
        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                title="Collapse">
          <i class="fa fa-minus"></i></button>
        <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fa fa-times"></i></button>
      </div>
    </div>
    <div class="box-body">
      Start creating your amazing application!
    </div>
    <div class="box-footer">
      Footer
    </div>
  </div>

</section>

{% endblock content %}

profiles/templates/profiles/user_admin_edit_password.html
{% extends "base.html" %}

{% block page_title %} Users {% endblock page_title %}


{% block content %}

<section class="content">

  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Edit User</h3>
    </div>

    <form class="form-horizontal" method="POST" novalidate>
      {% csrf_token %}
      <div class="box-body">
        <div class="form-group {% if form.password1.errors %} has-error {% endif %}">
          <label for="" class="col-md-2 control-label">Password:</label>
          <div class="col-md-4">
            {{ form.password1 }}
            <span class="help-block">{{ form.password1.errors }}</span>
          </div>
        </div>

        <div class="form-group {% if form.password2.errors %} has-error {% endif %}">
          <label for="" class="col-md-2 control-label">Password Confirmation:</label>
          <div class="col-md-4">
            {{ form.password2 }}
            <span class="help-block">{{ form.password2.errors }}</span>
          </div>
        </div>


      </div>

      <div class="box-footer">
        <button type="submit" class="btn btn-primary">Save</button>
      </div>

    </form>

  </div>


</section>

{% endblock content %}

{% block script %}

{% endblock script %}

profiles/templates/profiles/user_create.html
{% extends "base.html" %}

{% block page_title %} Users {% endblock page_title %}


{% block content %}

<section class="content">

  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Add User</h3>
    </div>

    <form class="form-horizontal" method="POST" novalidate>
      {% csrf_token %}
      <div class="box-body">
        <div class="form-group {% if form.group.errors %} has-error {% endif %}">
          <label for="" class="col-md-2 control-label">Group:</label>
          <div class="col-md-4">
            {{ form.group }}
            <span class="help-block">{{ form.group.errors }}</span>
          </div>
        </div>

        <div class="form-group {% if form.username.errors %} has-error {% endif %}">
          <label for="" class="col-md-2 control-label">Username:</label>
          <div class="col-md-4">
            {{ form.username }}
            <span class="help-block">{{ form.username.errors }}</span>
          </div>
        </div>

        <div class="form-group {% if form.password1.errors %} has-error {% endif %}">
          <label for="" class="col-md-2 control-label">Password:</label>
          <div class="col-md-4">
            {{ form.password1 }}
            <span class="help-block">{{ form.password1.errors }}</span>
          </div>
        </div>

        <div class="form-group {% if form.password2.errors %} has-error {% endif %}">
          <label for="" class="col-md-2 control-label">Password Confirmation:</label>
          <div class="col-md-4">
            {{ form.password2 }}
            <span class="help-block">{{ form.password2.errors }}</span>
          </div>
        </div>

        <div class="form-group {% if form.first_name.errors %} has-error {% endif %}">
          <label for="" class="col-md-2 control-label">First Name:</label>
          <div class="col-md-4">
            {{ form.first_name }}
            <span class="help-block">{{ form.first_name.errors }}</span>
          </div>
        </div>

        <div class="form-group {% if form.last_name.errors %} has-error {% endif %}">
          <label for="" class="col-md-2 control-label">Last Name:</label>
          <div class="col-md-4">
            {{ form.last_name }}
            <span class="help-block">{{ form.last_name.errors }}</span>
          </div>
        </div>

        <div class="form-group {% if form.email.errors %} has-error {% endif %}">
          <label for="" class="col-md-2 control-label">Email Address:</label>
          <div class="col-md-4">
            {{ form.email }}
            <span class="help-block">{{ form.email.errors }}</span>
          </div>
        </div>

        <div class="form-group">
          <label for="" class="col-md-2 control-label">Designation</label>
          <div class="col-md-4">
            {{ form.designation }}
          </div>
        </div>

        <div class="form-group">
          <label for="" class="col-md-2 control-label">Mobile Phone:</label>
          <div class="col-md-4">
            {{ form.mobile }}
          </div>
        </div>

        <div class="form-group">
          <label for="" class="col-md-2 control-label">Direct Line:</label>
          <div class="col-md-4">
            {{ form.direct_line }}
          </div>
        </div>

        <div class="form-group">
          <label for="" class="col-md-2 control-label">Other Phone:</label>
          <div class="col-md-4">
            {{ form.other_phone }}
          </div>
        </div>

        <div class="form-group">
          <label for="" class="col-md-2 control-label">Fax:</label>
          <div class="col-md-4">
            {{ form.fax }}
          </div>
        </div>

        <div class="form-group">
          <label for="" class="col-md-2 control-label">Notes:</label>
          <div class="col-md-4">
            {{ form.notes }}
          </div>
        </div>


      </div>

      <div class="box-footer">
        <button type="submit" class="btn btn-primary">Save</button>
      </div>

    </form>

  </div>


</section>

{% endblock content %}

{% block script %}

{% endblock script %}

profiles/templates/profiles/user_edit.html
{% extends "base.html" %}

{% block page_title %} Users {% endblock page_title %}


{% block content %}

<section class="content">

  <div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Edit User</h3>
    </div>

    <form class="form-horizontal" method="POST" novalidate>
      {% csrf_token %}
      <div class="box-body">
        <div class="form-group {% if form.group.errors %} has-error {% endif %}">
          <label for="" class="col-md-2 control-label">Group:</label>
          <div class="col-md-4">
            {{ form.group }}
            <span class="help-block">{{ form.group.errors }}</span>
          </div>
        </div>

        <div class="form-group {% if form.username.errors %} has-error {% endif %}">
          <label for="" class="col-md-2 control-label">Username:</label>
          <div class="col-md-4">
            {{ form.username }}
            <span class="help-block">{{ form.username.errors }}</span>
          </div>
        </div>

        <div class="form-group">
          <label for="" class="col-md-2 control-label"></label>
          <div class="col-md-4">
                <a href="{% url 'profiles:admin_password_update' id %}">Change password</a>
          </div>
        </div>

        <div class="form-group {% if form.first_name.errors %} has-error {% endif %}">
          <label for="" class="col-md-2 control-label">First Name:</label>
          <div class="col-md-4">
            {{ form.first_name }}
            <span class="help-block">{{ form.first_name.errors }}</span>
          </div>
        </div>

        <div class="form-group {% if form.last_name.errors %} has-error {% endif %}">
          <label for="" class="col-md-2 control-label">Last Name:</label>
          <div class="col-md-4">
            {{ form.last_name }}
            <span class="help-block">{{ form.last_name.errors }}</span>
          </div>
        </div>

        <div class="form-group {% if form.email.errors %} has-error {% endif %}">
          <label for="" class="col-md-2 control-label">Email Address:</label>
          <div class="col-md-4">
            {{ form.email }}
            <span class="help-block">{{ form.email.errors }}</span>
          </div>
        </div>

        <div class="form-group">
          <label for="" class="col-md-2 control-label">Designation</label>
          <div class="col-md-4">
            {{ form.designation }}
          </div>
        </div>

        <div class="form-group">
          <label for="" class="col-md-2 control-label">Mobile Phone:</label>
          <div class="col-md-4">
            {{ form.mobile }}
          </div>
        </div>

        <div class="form-group">
          <label for="" class="col-md-2 control-label">Direct Line:</label>
          <div class="col-md-4">
            {{ form.direct_line }}
          </div>
        </div>

        <div class="form-group">
          <label for="" class="col-md-2 control-label">Other Phone:</label>
          <div class="col-md-4">
            {{ form.other_phone }}
          </div>
        </div>

        <div class="form-group">
          <label for="" class="col-md-2 control-label">Fax:</label>
          <div class="col-md-4">
            {{ form.fax }}
          </div>
        </div>

        <div class="form-group">
          <label for="" class="col-md-2 control-label">Notes:</label>
          <div class="col-md-4">
            {{ form.notes }}
          </div>
        </div>


      </div>

      <div class="box-footer">
        <button type="submit" class="btn btn-primary">Save</button>
      </div>

    </form>

  </div>


</section>

{% endblock content %}

{% block script %}

{% endblock script %}

profiles/templates/profiles/user_list.html
{% extends "base.html" %}

{% block page_title %} Users {% endblock page_title %}


{% block content %}

<section class="content">

    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">User List</h3>
            <div class="box-tools pull-right">
                <a href="{% url 'profiles:create' %}" class="btn btn-success btn-sm">ADD USER <i class="fa fa-plus"></i></a>
            </div>
        </div>

        <div class="box-body">
            <table id="users-table" class="table table-bordered table-hover">
                <thead>
                    <tr>
                      <th>DATE ADDED</th>
                      <th>USER ID</th>
                      <th>FIRST NAME</th>
                      <th>LAST NAME</th>
                      <th>USER GROUP</th>
                      <th>EMAIL ADDRESS</th>
                      <th>-</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in object_list %}
                        <tr>
                            <td>{{ user.date_joined|date:"Y-m-d" }}</td>
                            <td>{{ user.user_id }}</td>
                            <td>{{ user.first_name }}</td>
                            <td>{{ user.last_name }}</td>
                            <td>{{ user.group }}</td>
                            <td>{{ user.email }}</td>
                            <td>
                              <a href="{% url 'profiles:update' user.id %}" class="pull-right text-blue"><i class="fa fa-pencil fa-lg" aria-hidden="true"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>

            </table>
        </div>
            <!-- /.box-body -->
    </div>
    <!-- /.box -->

</section>

{% endblock content %}

{% block script %}
    <script>
      $(function () {
        $('#users-table').DataTable({
          'paging'      : true,
          'lengthChange': true,
          'searching'   : true,
          'ordering'    : true,
          'info'        : true,
          'autoWidth'   : false
        })
      })
    </script>
{% endblock script %}