config/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from auth_login.forms import LoginForm

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', auth_views.LoginView.as_view(
        template_name='auth_login/login.html',
        authentication_form=LoginForm), name='login'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(
        next_page='/'), name='logout'),
    path('u/', include('profiles.urls'), name='profiles')
]

profiles/urls.py
from django.urls import path

from .views import ProfileListView
from . import views

app_name = 'profiles'

urlpatterns = [
    path('', ProfileListView.as_view(), name='list'),
    path('create/', views.profile_create, name='create'),
    path('<int:pk>/edit/', views.profile_edit, name='update'),
    path('<int:pk>/edit/password/', views.admin_edit_password, name='admin_password_update'),
    path('create/group/', views.group_create, name='create_group'),
]

config/templates/snippets/css.html
{% load static %}

<!-- Bootstrap 3.3.7 -->
<link rel="stylesheet" href="{% static "assets/components/bootstrap/dist/css/bootstrap.min.css" %}">
<!-- Font Awesome -->
<link rel="stylesheet" href="{% static "assets/components/font-awesome/css/font-awesome.min.css" %}">
<!-- Ionicons -->
<link rel="stylesheet" href="{% static "assets/components/Ionicons/css/ionicons.min.css" %}">
<!-- DataTables -->
  <link rel="stylesheet" href="{% static "assets/components/datatables.net-bs/css/dataTables.bootstrap.min.css" %}">
<!-- Theme style -->
<link rel="stylesheet" href="{% static "assets/dist/css/AdminLTE.min.css" %}">
<!-- AdminLTE Skins. Choose a skin from the css/skins
     folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href="{% static "assets/dist/css/skins/_all-skins.min.css" %}">

<link rel="stylesheet" href="{% static "assets/plugins/iCheck/square/blue.css" %}">

<!-- Custom CSS -->
<link rel="stylesheet" href="{% static "assets/dist/css/custom.css" %}">

config/templates/snippets/footer.html
<footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 2.0.0
    </div>
    <strong>Copyright &copy; 2017 <a href="#">Michael Cava</a>.</strong> All rights
    reserved.
</footer>

config/templates/snippets/js.html
{% load static %}

<!-- jQuery 3 -->
<script src="{% static "assets/components/jquery/dist/jquery.min.js" %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static "assets/components/jquery-ui/jquery-ui.min.js" %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static "assets/components/bootstrap/dist/js/bootstrap.min.js" %}"></script>
<!-- Morris.js charts -->
<script src="{% static "assets/components/raphael/raphael.min.js" %}"></script>
<script src="{% static "assets/components/morris.js/morris.min.js" %}"></script>
<!-- Sparkline -->
<script src="{% static "assets/components/jquery-sparkline/dist/jquery.sparkline.min.js" %}"></script>
<!-- jvectormap -->
<script src="{% static "assets/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js" %}"></script>
<script src="{% static "assets/plugins/jvectormap/jquery-jvectormap-world-mill-en.js" %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static "assets/components/jquery-knob/dist/jquery.knob.min.js" %}"></script>
<!-- daterangepicker -->
<script src="{% static "assets/components/moment/min/moment.min.js" %}"></script>
<script src="{% static "assets/components/bootstrap-daterangepicker/daterangepicker.js" %}"></script>
<!-- datepicker -->
<script src="{% static "assets/components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js" %}"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{% static "assets/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js" %}"></script>
<!-- DataTables -->
<script src="{% static "assets/components/datatables.net/js/jquery.dataTables.min.js" %}"></script>
<script src="{% static "assets/components/datatables.net-bs/js/dataTables.bootstrap.min.js" %}"></script>
<!-- Slimscroll -->
<script src="{% static "assets/components/jquery-slimscroll/jquery.slimscroll.min.js" %}"></script>
<!-- FastClick -->
<script src="{% static "assets/components/fastclick/lib/fastclick.js" %}"></script>
<!-- AdminLTE App -->
<script src="{% static "assets/dist/js/adminlte.min.js" %}"></script>

<script src="{% static "assets/plugins/iCheck/icheck.min.js" %}"></script>

config/templates/snippets/navbar.html
{% load static %}
<header class="main-header">
    <!-- Logo -->
    <a href="#" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>DC</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg">Django Core</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">

          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="{% static "assets/dist/img/default-avatar.jpg" %}" class="user-image" alt="User Image">
              <span class="hidden-xs">
                {% if user.is_authenticated %}
                  {{ user.get_full_name }}
                {% endif %}
              </span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="{% static "assets/dist/img/default-avatar.jpg" %}" class="img-circle" alt="User Image">

                <p>
                  {{ user.get_full_name }} - {{ user.get_username}}
                  <small>Member since Nov. 2012</small>
                </p>
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href="{% url 'logout' %}" class="btn btn-default btn-flat">Log out</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>

config/templates/snippets/sidebar.html
<!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">

    <section class="sidebar">

      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MAIN NAVIGATION</li>
        <li class="active">
          <a href="#">
            <i class="fa fa-dashboard"></i>
            <span>Dashboard</span>
          </a>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-users"></i>
            <span>Users</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{% url "profiles:list" %}"><i class="fa  fa-angle-double-right"></i> User List</a></li>
            <li><a href="#"><i class="fa  fa-angle-double-right"></i> Archived Users</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-cogs"></i>
            <span>Management</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{% url "profiles:create_group" %}"><i class="fa  fa-angle-double-right"></i>Add User Groups</a></li>
          </ul>
        </li>
      </ul>
    </section>

  </aside>